#!/bin/bash

# Get auth token
TOKEN=$(curl -s -X POST http://localhost:8080/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email":"admin@swift.com","password":"admin123"}' | jq -r '.token')

echo "Token: ${TOKEN:0:30}..."
echo ""
echo "Posting test message..."
echo ""

curl -v -X POST http://localhost:8080/api/messages \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "rawContent": ":20:LC12345\n:23:ISSUANCE OF A DOCUMENTARY CREDIT\n:31C:260131\n:40A:IRREVOCABLE\n:31D:251220\n:50:CITIBANK CORPORATION\n123 MAIN STREET\nNEW YORK NY 10001\n:59:DEUTDEFF MANUFACTURING\nPUDONG DISTRICT\nSHANGHAI CHINA\n:32B:USD 75000.00\n:39A:05/05\n:41D:DEUTDEFF INTERNATIONAL BANK\n:42C:DRAFTS AT SIGHT\n:43P:PARTIAL SHIPMENTS PROHIBITED\n:43T:TRANSSHIPMENT NOT ALLOWED\n:44A:COMMODITY: INDUSTRIAL MACHINERY\nQUANTITY: 25 UNITS\nUNIT PRICE: USD 3000.00\n:44E:SHANGHAI PORT, CHINA\n:44F:NEW YORK PORT, USA\n:44C:260115\n:45A:COMMERCIAL INVOICE IN TRIPLICATE\nPACKING LIST IN DUPLICATE\nCERTIFICATE OF ORIGIN\nINSURANCE CERTIFICATE\nBILL OF LADING\n:46A:INDUSTRIAL MACHINERY AS PER PURCHASE\nORDER NO. PO-2025-1234\n:71B:ALL BANKING CHARGES OUTSIDE\nOPENING BANK ARE FOR ACCOUNT\nOF BENEFICIARY\n:48:PERIOD FOR PRESENTATION 15 DAYS\n:49:CONFIRMATION INSTRUCTIONS IF ANY",
    "messageType": "MT700",
    "sender": "CITIBANKXX",
    "receiver": "DEUTDEFFXX",
    "buyerId": "CITIBANK",
    "sellerId": "DEUTDEFF"
  }'
